name: build

on: pull_request


jobs:
    build:
        runs-on: ubuntu-lastest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4.1.3

            - name: Setup Node.js
              uses: actions/setup-node@v4.0.2

            - name: Install Dependencies
              run: npm install
      
            - name: Build Project
              run: npm run build